### ISSUE TITLE
gin-cli formula: got this warning

### ISSUE THREAD

**Issue by jgrewe** [G-Node/homebrew-pkg#5]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the g-node/pkg tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/g-node/homebrew-pkg/Formula/gin-cli.rb:10

**Comment by danieltomasz** [comment]
I can confirm.

**Comment by achilleas-k** [comment]
I guess we just remove the line and it should be fine, right?

@jgrewe Can you delete the line in the formula and test it?

**Comment by jgrewe** [comment]
done with [6523740](https://github.com/G-Node/homebrew-pkg/commit/6523740ef5846c3faaac3e34b2fae96404282a31)
