### ISSUE TITLE
gin cli-formula error -> bottle :unneeded is disabled

### ISSUE THREAD

**Issue by moritzketzer** [G-Node/homebrew-pkg#7]
Hi, got the following message when I want to install Gin CLI:

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/g-node/homebrew-pkg/Formula/gin-cli.rb
gin-cli: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the g-node/pkg tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/g-node/homebrew-pkg/Formula/gin-cli.rb:10

Error: Cannot tap g-node/pkg: invalid syntax in tap!

**Comment by jgrewe** [comment]
@moritzketzer thanks for the report. Just updated the formula and removed the offending line. Seems to work fine locally on my machine now. It would be nice it you could you confirm this.

**Comment by moritzketzer** [comment]
@jgrewe thanks for the fast response, works!

**Comment by jgrewe** [comment]
@moritzketzer most welcome!
